<template>
    <div id="about" class="my-5">
        <div class="grid grid-cols-4 gap-5 dark:text-white">
            <div class="col-span-4 md:col-span-1 ">
                <side-list/>
            </div>
            <div class="col-span-4 md:col-span-3">
                <h5 class="text-3xl font-bold my-1">About Archive Viewer</h5>
                <p class="my-3">Twitter Archive Viewer is a complementary page to Archiver that allows offline reading of data
                    generated by <a href="https://github.com/BANKA2017/twitter-monitor/tree/node/apps/archiver" target="_blank" class="italic font-bold underline decoration-2 underline-offset-4 decoration-sky-500">Archiver()</a>.</p>
                <h5 class="text-3xl font-bold mb-1 mt-5">How to get archive</h5>

                <p class="my-3">
                    <ul role="list" class="marker:text-sky-400 list-disc pl-5 space-y-1">
                        <li>Shared by twitter monitor official.</li>
                        <li>Generate it by yourself via <a href="https://github.com/BANKA2017/twitter-monitor/tree/node/apps/archiver" target="_blank" class="italic font-bold underline decoration-2 underline-offset-4 decoration-sky-500">Archiver()</a>.</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import {useMainStore} from "~/stores/main";
import SideList from "~/components/SideList.vue";

useHead({
    title: 'About'
})
const store = useMainStore()

definePageMeta({
    layout: "archive-viewer",
})
</script>
