<template>
    <div id="about">
        <div class="grid grid-cols-4 gap-5 dark:text-white">
            <div class="col-span-4 md:col-span-1 ">
                <side-list/>
            </div>
            <div class="col-span-4 md:col-span-3">
                <h5 class="text-3xl font-bold">About Archive Viewer</h5>
                <p>Twitter Archive Viewer is a complementary page to Archiver that allows offline reading of data
                    generated by Archiver, and can back up most tweets from unprotected/undeleted/unbanned users within
                    the browser.</p>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import {useMainStore} from "~/stores/main";
import SideList from "~/components/SideList.vue";

useHead({
    title: 'About'
})
const store = useMainStore()

definePageMeta({
    layout: "archive-viewer",
})
</script>
